version: "3.9"
services:
  database:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - /data/redis:/usr/local/etc/redis


volumes:
  data: