version: "3.9"
services:
  database:
      container_name: postgres
      environment:
        POSTGRES_PASSWORD: example
        POSTGRES_USER: postgres
      image: postgres
      ports:
        - "5432:5432"
      restart: always
      volumes:
        - /data/postgres:/var/lib/postgresql/data

volumes:
  data: