version: "3.9"
services:
  cluster-master:
    container_name: cluster-master
    image: ipfs/ipfs-cluster
    depends_on:
      - ipfs-master
    environment:
      CLUSTER_PEERNAME: cluster
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
      CLUSTER_MONITORPINGINTERVAL: 2s
    ports:
      - "9094:9094"
      - "9096:9096"
    volumes:
      - /data/ipfs/clusters/0:/data/ipfs-cluster

  ipfs-master:
    container_name: ipfs-master
    image: ipfs/go-ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - /data/ipfs/peers/0:/data/ipfs

volumes:
  data: