version: '3.9'

services:
  mongo:
    container_name: stack-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - /data/mongo:/data/db
  
  mongo-express:
    container_name: stack-mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/